import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react-swc'
import { copyFileSync, existsSync, mkdirSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

// Get __dirname equivalent in ES modules
const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

// Plugin to copy contentData.js to dist/data during build
const copyContentDataPlugin = () => {
  return {
    name: 'copy-content-data',
    closeBundle() {
      // After build completes, copy contentData.js to dist/data
      const srcFile = resolve(__dirname, 'src/data/contentData.js')
      const distDataDir = resolve(__dirname, 'dist/data')
      const distFile = resolve(distDataDir, 'contentData.js')
      
      if (existsSync(srcFile)) {
        // Create dist/data directory if it doesn't exist
        if (!existsSync(distDataDir)) {
          mkdirSync(distDataDir, { recursive: true })
        }
        
        // Copy the file
        copyFileSync(srcFile, distFile)
        console.log('✅ Copied contentData.js to dist/data/')
      } else {
        console.warn('⚠️  contentData.js not found in src/data/ - will be generated by backend')
      }
    }
  }
}

// https://vite.dev/config/
export default defineConfig(({ mode }) => {
  const buildTimestamp = new Date().toISOString();
  const isProduction = mode === 'production';
  
  console.log(`\n🏗️  Building in ${mode} mode`);
  console.log(`📅 Build timestamp: ${buildTimestamp}\n`);
  
  return {
    plugins: [react(), copyContentDataPlugin()],
    
    server: {
      port: 5173,
      proxy: {
        '/api': {
          target: 'http://localhost:8000',
          changeOrigin: true,
        },
        '/uploads': {
          target: 'http://localhost:8000',
          changeOrigin: true,
        },
      },
    },
    
    build: {
      outDir: 'dist',
      sourcemap: !isProduction, // Only in dev
      // Optimize chunks for better loading
      rollupOptions: {
        output: {
          // Add hash to filenames for cache busting
          entryFileNames: 'assets/[name]-[hash].js',
          chunkFileNames: 'assets/[name]-[hash].js',
          assetFileNames: 'assets/[name]-[hash].[ext]',
          manualChunks: {
            'react-vendor': ['react', 'react-dom', 'react-router-dom'],
            'ui-vendor': ['framer-motion', 'react-slick', 'slick-carousel'],
            'form-vendor': ['react-hook-form', 'react-quill', 'react-dropzone'],
            'utils-vendor': ['axios', '@tanstack/react-query', 'zustand', 'date-fns', 'clsx'],
          },
        },
      },
      // Increase chunk size warning limit
      chunkSizeWarningLimit: 1000,
    },
    
    // Define app metadata
    define: {
      __APP_NAME__: JSON.stringify('Eagle Chair'),
      __APP_VERSION__: JSON.stringify('1.0.0'),
      __BUILD_TIMESTAMP__: JSON.stringify(buildTimestamp),
    },
  };
});
