"""Add CMS fields: image_url to Feature and CompanyValue, subtitle to CompanyValue, enhance Installation images JSON

Revision ID: 89df2a1977d1
Revises: 5b8afc65b18a
Create Date: 2025-10-26 09:30:22.903925

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '89df2a1977d1'
down_revision = '5b8afc65b18a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_values', sa.Column('subtitle', sa.String(length=500), nullable=True))
    op.add_column('company_values', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('features', sa.Column('image_url', sa.String(length=500), nullable=True))
    
    # Convert installations.images from VARCHAR to JSON with explicit USING clause
    op.execute('ALTER TABLE installations ALTER COLUMN images TYPE JSON USING images::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert installations.images from JSON back to VARCHAR
    op.execute('ALTER TABLE installations ALTER COLUMN images TYPE VARCHAR USING images::text')
    
    op.drop_column('features', 'image_url')
    op.drop_column('company_values', 'image_url')
    op.drop_column('company_values', 'subtitle')
    # ### end Alembic commands ###

